---
- name: Include vars
  ansible.builtin.import_tasks: include-vars.yml

- name: Include setup tasks
  ansible.builtin.import_tasks: setup.yml
  when: not redis_server_remove | bool
  tags: redis

- name: Include remove tasks
  ansible.builtin.import_tasks: remove.yml
  when: redis_server_remove | bool
  tags:
    - redis
    - remove
