---

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  when: not alloy_remove
  tags:
    - alloy

- name: Include remove tasks
  ansible.builtin.include_tasks: remove.yml
  tags:
    - alloy
    - remove
  when: alloy_remove
