---

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  when: not grafana_remove | bool
  tags:
    - grafana
    - loki

- name: Include remove tasks
  ansible.builtin.include_tasks: remove.yml
  when: grafana_remove | bool
  tags:
    - grafana
    - remove
