---

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  tags:
    - gitlab_runner
  when: not gitlab_runner_remove

- name: Include remove tasks
  ansible.builtin.import_tasks: remove.yml
  tags:
    - gitlab-runner
  when: gitlab_runner_remove
