---
dependencies:
  - role: alphanodes.setup.common
    public: true
  - role: alphanodes.setup.drush
  - role: alphanodes.setup.ssl
  - role: alphanodes.setup.memcached
  - role: alphanodes.setup.php_fpm
  - role: alphanodes.setup.nginx

galaxy_info:
  description: Setup drupal
  author: alexandermeindl
  company: AlphaNodes GmbH
  license: Apache License 2.0
  min_ansible_version: '2.16'
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
  galaxy_tags:
    - drupal
