---

matomo_working_dir: /tmp/matomo_source

matomo_available_plugins:
  CustomVariables:
    use_git: true
    repo: https://github.com/matomo-org/plugin-CustomVariables.git
    download: https://github.com/matomo-org/plugin-CustomVariables/archive/%%version%%.tar.gz
    version: 5.0.4
  QueuedTracking:
    use_git: false
    repo: https://github.com/matomo-org/plugin-QueuedTracking.git
    download: https://github.com/matomo-org/plugin-QueuedTracking/archive/%%version%%.tar.gz
    version: 5.2.0
  LoginLdap:
    use_git: true
    repo: https://github.com/matomo-org/plugin-LoginLdap.git
    download: https://github.com/matomo-org/plugin-LoginLdap/archive/%%version%%.tar.gz
    version: 5.1.6
    branch: 5.1.6
  MarketingCampaignsReporting:
    use_git: true
    repo: https://github.com/matomo-org/plugin-MarketingCampaignsReporting.git
    download: https://github.com/matomo-org/plugin-MarketingCampaignsReporting/archive/%%version%%.tar.gz
    version: 5.1.5
    branch: 5.1.5
  Migration:
    use_git: true
    repo: https://github.com/matomo-org/plugin-Migration.git
    download: https://github.com/matomo-org/plugin-Migration/archive/%%version%%.tar.gz
    version: 5.0.6
  Provider:
    use_git: true
    repo: https://github.com/matomo-org/plugin-Provider.git
    download: https://github.com/matomo-org/plugin-Provider/archive/%%version%%.tar.gz
    version: 5.0.4
  SecurityInfo:
    use_git: true
    repo: https://github.com/matomo-org/plugin-SecurityInfo.git
    download: https://github.com/matomo-org/plugin-SecurityInfo/archive/%%version%%.tar.gz
    version: 5.0.4
