---

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  tags: nginx

- name: Include microcache tasks
  ansible.builtin.include_tasks: microcache.yml
  tags: nginx
  when: nginx_fastcgi_microcache_zone | length > 0

- name: Include instance tasks
  ansible.builtin.include_tasks: instance.yml
  tags: nginx
  loop: '{{ nginx_vhosts }}'
  loop_control:
    loop_var: instance
  when:
    - nginx_vhosts | length > 0
    - nginx_mono_service_name is not defined  # Skip in service mode (mailpit, etc.)

- name: Include service integration tasks
  ansible.builtin.include_tasks: service.yml
  tags: nginx
  when:
    - nginx_mono_service_name is defined
    - nginx_mono_service_config is defined
