---
dependencies:
  - role: alphanodes.setup.common
    public: true
  - role: alphanodes.setup.mysql

galaxy_info:
  description: Setup dovecot
  author: alexandermeindl
  company: AlphaNodes GmbH
  license: Apache License 2.0
  min_ansible_version: '2.18'
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - dovecot
