---
dependencies:
  - role: alphanodes.setup.common
    public: true
  - role: alphanodes.setup.php_cli
  - role: alphanodes.setup.composer
    tags:
      - drush
      - composer

galaxy_info:
  description: Setup drush
  author: alexandermeindl
  company: AlphaNodes GmbH
  license: Apache License 2.0
  min_ansible_version: '2.18'
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
