---

- name: Install ruby build packages
  ansible.builtin.include_role:
    name: alphanodes.setup.ruby
  vars:
    ruby_build: true

- name: Detect rubies
  ansible.builtin.command: '{{ rvm1_rvm }} list strings'
  register: rvm_list_strings
  changed_when: false

- name: Install rubies
  ansible.builtin.command: '{{ rvm1_rvm }} install {{ item }} {{ rvm1_ruby_install_flags }}'
  loop: '{{ rvm1_rubies | difference(rvm_list_strings.stdout_lines) }}'

- name: Detect default ruby version
  ansible.builtin.command: '{{ rvm1_rvm }} alias list default'
  changed_when: false
  register: detect_default_ruby_version

- name: Select default ruby
  ansible.builtin.command: '{{ rvm1_rvm }} alias create default {{ rvm1_default_ruby_version }}'
  when: detect_default_ruby_version.stdout|default() | length == 0 or
        rvm1_default_ruby_version not in detect_default_ruby_version.stdout

- name: Detect installed ruby patch number
  ansible.builtin.shell: >
    set -o pipefail &&
    {{ rvm1_rvm }} list strings |
    grep {{ item }} |
    tail -n 1
  args:
    executable: /bin/bash
  loop: '{{ rvm1_rubies }}'
  changed_when: false
  register: ruby_patch
  # Run in normal mode when in --check mode (http://docs.ansible.com/ansible/playbooks_checkmode.html)
  check_mode: false

- name: Install bundler if not installed
  ansible.builtin.shell: >
    set -o pipefail &&
    ls {{ rvm1_install_path }}/wrappers/{{ item.stdout }} |
    if ! grep "^bundler " ; then {{ rvm1_install_path }}/wrappers/{{ item.stdout }}/gem install bundler ; fi
  args:
    executable: /bin/bash
    creates: '{{ rvm1_install_path }}/wrappers/{{ item.stdout }}/bundler'
  loop: '{{ ruby_patch.results }}'
  when: rvm1_bundler_install
  register: bundler_install
  changed_when: '"Successfully installed bundler" in bundler_install.stdout'

- name: Symlink ruby related binaries on the system path
  ansible.builtin.file:
    state: 'link'
    src: '{{ rvm1_install_path }}/wrappers/default/{{ item }}'
    dest: '{{ rvm1_symlink_to }}/{{ item }}'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    follow: false
  when: not '--user-install' in rvm1_install_flags and rvm1_symlink
  loop: '{{ rvm1_symlink_binaries }}'

- name: Symlink bundler binaries on the system path
  ansible.builtin.file:
    state: 'link'
    src: '{{ rvm1_install_path }}/wrappers/default/{{ item }}'
    dest: '{{ rvm1_symlink_to }}/{{ item }}'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    follow: false
  when: not '--user-install' in rvm1_install_flags and rvm1_bundler_install and rvm1_symlink
  loop: '{{ rvm1_symlink_bundler_binaries }}'

- name: Delete ruby if relevant
  ansible.builtin.command: '{{ rvm1_rvm }} remove {{ rvm1_delete_ruby }}'
  register: rvm_delete_command
  changed_when: "'#removing' in rvm_delete_command.stdout"
  when: rvm1_delete_ruby is defined and rvm1_delete_ruby | length > 0
