---
dependencies: []

galaxy_info:
  description: Node.js installation
  author: alexandermeindl
  company: AlphaNodes GmbH
  license: Apache License 2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
        - trixie

  galaxy_tags:
    - javascript
    - js
    - node
    - npm
    - nodejs
