---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: Restart rspamd
  ansible.builtin.systemd_service:
    name: rspamd
    state: restarted
