---
dependencies: []

galaxy_info:
  description: ssh server with ssh key management (private keys, authorized_keys) and use based known_hosts support
  author: alexandermeindl
  company: AlphaNodes GmbH
  license: Apache License 2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
  galaxy_tags:
    - ssh
    - sftp
    - keys
    - publickey
    - security
    - users
