---
- name: Determine certificate name
  ansible.builtin.set_fact:
    cert_item_name: "{{ cert_item.name | default(cert_item.domains | first | replace('*.', '')) }}"

- name: Check if certificate already exists
  ansible.builtin.stat:
    path: /etc/letsencrypt/live/{{ cert_item_name }}/cert.pem
  register: letsencrypt_cert

- name: Ensure pre and post hook folders exist
  ansible.builtin.file:
    path: /etc/letsencrypt/renewal-hooks/{{ item }}
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop:
    - pre
    - post

- name: Create pre hook to stop services
  ansible.builtin.template:
    src: stop_services.j2
    dest: /etc/letsencrypt/renewal-hooks/pre/stop_services
    owner: root
    group: root
    mode: "0750"
  when:
    - certbot_create_standalone_stop_services is defined
    - certbot_create_standalone_stop_services | length > 0

- name: Create post hook to start services
  ansible.builtin.template:
    src: start_services.j2
    dest: /etc/letsencrypt/renewal-hooks/post/start_services
    owner: root
    group: root
    mode: "0750"
  when:
    - certbot_create_standalone_stop_services is defined
    - certbot_create_standalone_stop_services | length > 0

- name: Check if domains have changed
  when: letsencrypt_cert.stat.exists
  block:
    - name: Register certificate domains
      ansible.builtin.shell: |
        set -o pipefail
        {{ certbot_script }} certificates --cert-name {{ cert_item_name }} | grep Domains | cut -d':' -f2
      args:
        executable: /bin/bash
      changed_when: false
      register: letsencrypt_cert_domains_dirty

    - name: Cleanup domain list
      ansible.builtin.set_fact:
        letsencrypt_cert_domains: >-
          {{ letsencrypt_cert_domains_dirty.stdout | trim | split(' ') |
             map('trim') | select('!=', '') | list | sort }}

    - name: Determine if domains have changed
      ansible.builtin.set_fact:
        letsencrypt_cert_domains_changed: >-
          {{ letsencrypt_cert_domains != (cert_item.domains |
             map('trim') | select('!=', '') | list | sort) }}

- name: Generate new certificate if one doesn't exist
  ansible.builtin.command: "{{ certbot_create_command }}"
  register: certbot_create_result
  changed_when: certbot_create_result.rc == 0
  when: not letsencrypt_cert.stat.exists or letsencrypt_cert_domains_changed | default(false)
