---

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  when: not mail_autoconfig_remove
  tags:
    - mail_autoconfig

- name: Include nginx tasks
  ansible.builtin.include_tasks: nginx.yml
  when: not mail_autoconfig_remove
  tags:
    - mail_autoconfig
    - nginx

- name: Include remove tasks
  ansible.builtin.include_tasks: remove.yml
  when: mail_autoconfig_remove
  tags:
    - mail_autoconfig
    - remove
