---
dependencies:
  - role: alphanodes.setup.ssl
  - role: alphanodes.setup.nginx

galaxy_info:
  description: Setup jekyll
  author: alexandermeindl
  company: AlphaNodes GmbH
  license: Apache License 2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
