---

python_packages:
  - python3-pip
  - python3-virtualenv

python_with_dev: false

python_pip_packages: []

python_pip_default_state: latest
python_pip_virtualenv_site_packages: false

# python_pip_default_venv: yourenv

python_venv_parent: "{{ ansible_facts['env']['HOME'] }}/.venvs"
