---
dependencies:
  - role: alphanodes.setup.common
    public: true
  - role: alphanodes.setup.php_fpm
  - role: alphanodes.setup.postgresql
  - role: alphanodes.setup.nginx_mono
  - role: alphanodes.setup.zabbix_agent

galaxy_info:
  description: Setup zabbix server
  author: alexandermeindl
  company: AlphaNodes GmbH
  license: MIT
  min_ansible_version: '2.18'
  platforms:
    - name: Ubuntu
      versions:
        - noble
    - name: Debian
      versions:
        - bookworm
        - trixie
