---
dependencies:
  - { role: alphanodes.setup.postgresql_client }

galaxy_info:
  author: alexandermeindl
  description: PostgreSQL server for Debian and Ubuntu.
  company: AlphaNodes GmbH
  license: Apache License 2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
  galaxy_tags:
    - database
    - postgresql
    - postgres
    - rdbms
