---
galaxy_info:
  author: AlphaNodes
  description: Install and configure Grafana Alloy for log shipping to Loki
  license: MIT
  min_ansible_version: '2.18'
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - noble

dependencies:
  - role: alphanodes.setup.common
    public: true
