---
dependencies: []

galaxy_info:
  author: alexandermeindl
  company: AlphaNodes GmbH
  description: Setup memcached
  license: Apache License 2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
        - trixie
  galaxy_tags:
    - web
    - database
    - memcached
    - keyvalue
    - kv
    - cache
    - caching
    - performance
