---
name: "alphanodes.setup.nextcloud"
"on":
  pull_request:
    paths:
      - roles/nextcloud/**
      - roles/nginx_mono/**
      - molecule/nextcloud/**
      - .github/workflows/nextcloud.yml
  push:
    paths:
      - roles/nextcloud/**
      - roles/nginx_mono/**
      - molecule/nextcloud/**
      - .github/workflows/nextcloud.yml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env: {}
    strategy:
      matrix:
        distro:
          - ubuntu2404
          - debian12
          - debian13
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install test dependencies
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule tests
        run: molecule test -s nextcloud
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
