---
name: "alphanodes.setup.vimbadmin"
'on':
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'roles/vimbadmin/**'
      - 'roles/common/**'
      - 'roles/nginx_mono/**'
      - 'roles/ssl/**'
      - 'roles/php_fpm/**'
      - 'roles/mysql/**'
      - 'roles/mysql_client/**'
      - 'roles/composer/**'
      - 'roles/memcached/**'
      - 'roles/postfix/**'
      - 'roles/dovecot/**'
      - 'molecule/vimbadmin/**'
      - '.github/workflows/vimbadmin.yml'

defaults:
  run:
    working-directory: 'vimbadmin'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    strategy:
      matrix:
        distro:
          - debian13

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5
        with:
          path: 'vimbadmin'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install test dependencies.
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Molecule tests.
        run: |
          molecule --version
          molecule test -s vimbadmin
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
